### ISSUE TITLE
docker compose -f docker-compose.cluster.yml - error out

### ISSUE THREAD

**Issue by AndriyKalashnykov** [OneCricketeer/apache-kafka-connect-docker#38]
Several occurances of the following as result of configuration:
```
pache-kafka-connect-docker-kafka-controller-1  | Exception in thread "main" 
apache-kafka-connect-docker-kafka-controller-1  | java.lang.IllegalArgumentException: requirement failed: The advertised.listeners config must be empty when process.roles=controller
```
among other errors. See full log attached - [error.log](https://github.com/OneCricketeer/apache-kafka-connect-docker/files/12263685/error.log)

**Comment by OneCricketeer** [comment]
Oh. The bitnami container just had a refactoring! I've not gotten around to testing that yet. 

You should be able to run this using 3.4.1 image tag for the broker.
